import {describe,expect,it,vi} from 'vitest';
import {loadConfig} from '../config/env.js';
import {createDiscordClient,drainDiscordInteractions} from './client.js';
const config=loadConfig({DISCORD_TOKEN:'d',DISCORD_CLIENT_ID:'123456789012346',DISCORD_GUILD_ID:'123456789012345',ADMIN_USER_ID:'234567890123456',BOT_COMMAND_CHANNEL_ID:'345678901234567',FISH_API_KEY:'f',DATABASE_URL:'file:/x'} as NodeJS.ProcessEnv);
const interaction=(commandName:string,userId='456789012345678',channelId=config.BOT_COMMAND_CHANNEL_ID)=>({isButton:()=>false,isChatInputCommand:()=>true,isCommand:()=>true,isRepliable:()=>true,commandName,guildId:config.DISCORD_GUILD_ID,channelId,user:{id:userId},guild:{},options:{getUser:()=>({id:'567890123456789'}),getSubcommand:()=> 'status'},reply:vi.fn(async()=>{}),followUp:vi.fn(async()=>{})});
const harness=(paused=false)=>{const state={isPaused:vi.fn(()=>paused),setPaused:vi.fn(),backupStatus:vi.fn(),operationalError:vi.fn(),recordOperationalError:vi.fn()},repo={voiceByOwner:vi.fn(),deleteOwnerDataAndQueue:vi.fn(),resetVoiceDataAndQueue:vi.fn(),voices:vi.fn(()=>[])},services={state,capture:{stopAllAndDrain:vi.fn(),removeUserAndDrain:vi.fn()},training:{stop:vi.fn(),status:vi.fn(),cancelUser:vi.fn()},voice:{stopAll:vi.fn(),cancelGroupAndDrain:vi.fn()},samples:{list:vi.fn(()=>[]),modelEligible:vi.fn(()=>[]),cleanupQueuedFiles:vi.fn()},providerDeletions:{},fish:{},builder:{}} as any;return {state,repo,services,client:createDiscordClient(config,repo as any,services)};};
describe('command control authorization',()=>{
 it.each(['deletedata','deletevoice','pause','start'])('rejects non-admin /%s before all side effects',async command=>{const h=harness(command==='start'),i=interaction(command);h.client.emit('interactionCreate',i as any);await drainDiscordInteractions(h.client);expect(i.reply).toHaveBeenCalledWith({content:'Only the configured bot administrator can use this command.'});expect(h.state.setPaused).not.toHaveBeenCalled();expect(h.repo.deleteOwnerDataAndQueue).not.toHaveBeenCalled();expect(h.repo.resetVoiceDataAndQueue).not.toHaveBeenCalled();expect(h.services.capture.stopAllAndDrain).not.toHaveBeenCalled();expect(h.services.capture.removeUserAndDrain).not.toHaveBeenCalled();});
 it('keeps persisted pause and reports a failed drain honestly',async()=>{const h=harness(),i=interaction('pause',config.ADMIN_USER_ID);h.services.capture.stopAllAndDrain.mockRejectedValue(new Error('capture failed'));h.client.emit('interactionCreate',i as any);await drainDiscordInteractions(h.client);expect(h.state.setPaused).toHaveBeenCalledWith(true);expect(h.state.recordOperationalError).toHaveBeenCalled();expect(i.reply).toHaveBeenCalledWith({content:'Bot is paused, but one or more operations did not drain cleanly; check /diagnostics.'});});
 it('rejects the configured administrator in the wrong channel before side effects',async()=>{const h=harness(),i=interaction('pause',config.ADMIN_USER_ID,'678901234567890');h.client.emit('interactionCreate',i as any);await drainDiscordInteractions(h.client);expect(i.reply).toHaveBeenCalledWith({content:'Bot commands are only allowed in the configured command channel.'});expect(h.state.setPaused).not.toHaveBeenCalled();});
});
