import {access,mkdir,readdir,realpath,rm,stat} from 'node:fs/promises';import path from 'node:path';
import type {DB} from '../client.js';
import type {ScoredSample} from '../../training/types.js';
export interface StorageReservation {bind(filePath:string):void;commit():void;release():void}
export interface PurgeResult {tombstoned:number;deletedFiles:number;cleanupFailures:unknown[]}

export class SampleRepository {
  private reservationTail:Promise<void>=Promise.resolve();
  private reservedBytes=0;private reservedFiles=new Set<string>();
  constructor(private db:DB,private managedRoot='/data/training'){}
  private isManaged(file:string,root=this.managedRoot){const managed=path.resolve(root),parts=path.relative(managed,path.resolve(file)).split(path.sep);return !parts.includes('..')&&parts.length===3&&/^\d{15,22}$/.test(parts[0]!)&&/^\d{15,22}$/.test(parts[1]!)&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.wav$/i.test(parts[2]!);}
  async isSafeManagedFile(file:string,root=this.managedRoot){if(!this.isManaged(file,root))return false;try{const canonicalRoot=await realpath(root),canonicalFile=await realpath(file);return canonicalFile.startsWith(`${canonicalRoot}${path.sep}`)&&this.isManaged(canonicalFile,canonicalRoot);}catch{return false;}}
  private async removeManaged(file:string,root=this.managedRoot){if(!this.isManaged(file,root))throw new Error('Refusing to delete a file outside managed training storage');const exists=await access(file).then(()=>true,()=>false);if(exists&&!await this.isSafeManagedFile(file,root))throw new Error('Refusing to delete a managed path that escapes through a symlink');await rm(path.resolve(file),{force:true});}
  save(guild:string,s:ScoredSample){
    if(!s.filePath)throw new Error('A captured sample must have a file');
    this.db.prepare(`INSERT INTO samples(id,guild_id,voice_owner_id,file_path,duration_ms,captured_at,transcript,quality_score,speech_ratio,rms,peak,clipping_ratio,snr_estimate,reasons,is_best,exceptional,selected,review_status,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(s.id,guild,s.ownerId,s.filePath,Math.round(s.durationMs),s.capturedAt,s.transcript??null,s.qualityScore,s.speechRatio,s.rms,s.peak,s.clippingRatio,s.snrEstimate,JSON.stringify(s.reasons),+s.isBestSample,+s.exceptionalCandidate,+s.selectedForRebuild,s.reviewStatus??'pending',+s.active);
  }
  async remove(id:string){const sample=this.get(id);if(!sample)return;this.db.prepare('UPDATE samples SET active=0,is_best=0,selected=0 WHERE id=?').run(id);if(sample.filePath)await this.removeManaged(sample.filePath);this.db.transaction(()=>{this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?').run(id);this.db.prepare('DELETE FROM samples WHERE id=? AND active=0').run(id);})();}
  list(guild:string,owner?:string,active=true){const rows=this.db.prepare(`SELECT * FROM samples WHERE guild_id=? ${owner?'AND voice_owner_id=?':''} ${active?'AND active=1':''} ORDER BY quality_score DESC`).all(...(owner?[guild,owner]:[guild])) as any[];return rows.map(row=>this.map(row));}
  eligible(guild:string,owner:string){return this.list(guild,owner).filter(s=>s.reviewStatus!=='rejected');}
  modelEligible(guild:string,owner:string,minScore:number){return this.list(guild,owner).filter(sample=>sample.reviewStatus==='accepted'||sample.reviewStatus==='pending'&&sample.qualityScore>=minScore);}
  selectedStillUsable(guild:string,owner:string,ids:string[]){if(!ids.length)return false;const placeholders=ids.map(()=>'?').join(',');const row=this.db.prepare(`SELECT COUNT(*) count FROM samples WHERE guild_id=? AND voice_owner_id=? AND active=1 AND review_status!='rejected' AND id IN (${placeholders})`).get(guild,owner,...ids) as {count:number};return row.count===ids.length;}
  pendingReviewCandidates(guild:string,owner:string){return this.list(guild,owner).filter(s=>s.reviewStatus==='pending');}
  get(id:string){const row=this.db.prepare('SELECT * FROM samples WHERE id=?').get(id) as any;return row?this.map(row):undefined;}
  review(id:string,reviewer:string,decision:'accepted'|'rejected'){const value=decision==='accepted';return this.db.transaction(()=>{const changed=this.db.prepare("UPDATE samples SET selected=?,is_best=?,review_status=? WHERE id=? AND active=1 AND review_status='pending'").run(+value,+value,decision,id).changes;if(changed)this.db.prepare('INSERT INTO sample_reviews(sample_id,reviewer_id,decision,created_at) VALUES(?,?,?,?)').run(id,reviewer,decision,Date.now());return changed;})();}
  history(guild:string,owner:string){return this.db.prepare('SELECT r.*,s.quality_score,s.duration_ms FROM sample_reviews r JOIN samples s ON s.id=r.sample_id WHERE s.guild_id=? AND s.voice_owner_id=? ORDER BY r.created_at DESC LIMIT 20').all(guild,owner) as any[];}
  async clear(guild:string,owner?:string){return this.purge(guild,owner);}
  async purge(guild:string,owner?:string):Promise<PurgeResult>{const samples=this.list(guild,owner,false);const deactivate=this.db.prepare('UPDATE samples SET active=0,is_best=0,selected=0 WHERE id=?');this.db.transaction(()=>samples.forEach(sample=>deactivate.run(sample.id)))();const cleanupFailures:unknown[]=[];let deletedFiles=0;for(const sample of samples){try{if(sample.filePath)await this.removeManaged(sample.filePath);deletedFiles++;this.db.transaction(()=>{this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?').run(sample.id);this.db.prepare('DELETE FROM samples WHERE id=? AND active=0').run(sample.id);})();}catch(error){cleanupFailures.push(error);}}return {tombstoned:samples.length,deletedFiles,cleanupFailures};}
  async cleanupQueuedFiles(paths?:string[]):Promise<PurgeResult>{const rows=paths?.map(file_path=>({file_path}))??this.db.prepare('SELECT file_path FROM pending_local_file_deletions WHERE retryable=1 AND next_retry_at<=?').all(Date.now()) as {file_path:string}[];const cleanupFailures:unknown[]=[];let deletedFiles=0;for(const row of rows){const exists=await access(row.file_path).then(()=>true,()=>false),permanent=!this.isManaged(row.file_path)||(exists&&!await this.isSafeManagedFile(row.file_path));try{await this.removeManaged(row.file_path);this.db.prepare('DELETE FROM pending_local_file_deletions WHERE file_path=?').run(row.file_path);deletedFiles++;}catch(error){cleanupFailures.push(error);this.db.prepare('UPDATE pending_local_file_deletions SET attempts=attempts+1,last_error=?,next_retry_at=?,retryable=? WHERE file_path=?').run(error instanceof Error?error.message:'cleanup failed',Date.now()+60_000,+!permanent,row.file_path);}}return {tombstoned:rows.length,deletedFiles,cleanupFailures};}
  async cleanupTombstones(ids:string[]):Promise<PurgeResult>{const cleanupFailures:unknown[]=[];let deletedFiles=0;for(const id of ids){const sample=this.get(id);if(!sample||sample.active)continue;try{if(sample.filePath)await this.removeManaged(sample.filePath);deletedFiles++;this.db.transaction(()=>{this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?').run(id);this.db.prepare('DELETE FROM samples WHERE id=? AND active=0').run(id);})();}catch(error){cleanupFailures.push(error);}}return {tombstoned:ids.length,deletedFiles,cleanupFailures};}
  async deactivate(ids:string[]):Promise<PurgeResult>{const samples=ids.map(id=>this.get(id)).filter((s):s is ScoredSample=>!!s);const stmt=this.db.prepare('UPDATE samples SET active=0,is_best=0,selected=0 WHERE id=?');this.db.transaction(()=>ids.forEach(id=>stmt.run(id)))();return this.cleanupTombstones(samples.map(sample=>sample.id));}
  markBest(id:string){const sample=this.get(id);if(!sample||!sample.active||sample.reviewStatus!=='pending')return;this.db.transaction(()=>{this.db.prepare("UPDATE samples SET is_best=0 WHERE guild_id=(SELECT guild_id FROM samples WHERE id=?) AND voice_owner_id=? AND review_status='pending'").run(id,sample.ownerId);this.db.prepare("UPDATE samples SET is_best=1 WHERE id=? AND active=1 AND review_status='pending'").run(id);})();}
  refreshPendingBest(guild:string,owner:string,minScore:number,minDurationMs:number,maxDurationMs:number){const best=this.pendingReviewCandidates(guild,owner).find(sample=>sample.qualityScore>=minScore&&sample.durationMs>=minDurationMs&&sample.durationMs<=maxDurationMs);this.db.transaction(()=>{this.db.prepare("UPDATE samples SET is_best=0 WHERE guild_id=? AND voice_owner_id=? AND review_status='pending'").run(guild,owner);if(best)this.db.prepare("UPDATE samples SET is_best=1 WHERE id=? AND active=1 AND review_status='pending'").run(best.id);})();return best;}
  async reconcileManagedStorage(root=this.managedRoot){
    const managed=path.resolve(root);await mkdir(managed,{recursive:true});const rows=this.db.prepare('SELECT id,file_path,active FROM samples').all() as {id:string;file_path:string;active:number}[];const pending=new Set((this.db.prepare('SELECT file_path FROM pending_local_file_deletions').all() as {file_path:string}[]).map(row=>path.resolve(row.file_path)));const referenced=new Set<string>(pending),missing:string[]=[],finishedTombstones:string[]=[];const generated=(file:string)=>this.isManaged(file,managed);
    for(const row of rows){const file=path.resolve(row.file_path);if(!generated(file)){if(row.active)missing.push(row.id);continue;}const absent=await access(file).then(()=>false,()=>true);if(row.active){if(absent||!await this.isSafeManagedFile(file,managed))missing.push(row.id);else referenced.add(file);}else if(absent)finishedTombstones.push(row.id);else try{await this.removeManaged(file,managed);finishedTombstones.push(row.id);}catch{referenced.add(file);}}
    if(missing.length){const update=this.db.prepare('UPDATE samples SET active=0,is_best=0,selected=0 WHERE id=?');this.db.transaction(()=>missing.forEach(id=>update.run(id)))();}
    if(finishedTombstones.length){const reviews=this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?'),remove=this.db.prepare('DELETE FROM samples WHERE id=? AND active=0');this.db.transaction(()=>finishedTombstones.forEach(id=>{reviews.run(id);remove.run(id)}))();}
    const guilds=await readdir(managed,{withFileTypes:true});let removed=0;const cleanupFailures:unknown[]=[];for(const guild of guilds){if(!guild.isDirectory()||!/^\d{15,22}$/.test(guild.name))continue;const guildPath=path.join(managed,guild.name);for(const owner of await readdir(guildPath,{withFileTypes:true}).catch(()=>[])){if(!owner.isDirectory()||!/^\d{15,22}$/.test(owner.name))continue;const ownerPath=path.join(guildPath,owner.name);for(const entry of await readdir(ownerPath,{withFileTypes:true}).catch(()=>[])){if(!entry.isFile())continue;const file=path.resolve(ownerPath,entry.name);if(generated(file)&&!referenced.has(file)&&!this.reservedFiles.has(file)){try{await this.removeManaged(file,managed);removed++;}catch(error){cleanupFailures.push(error);}}}}}
    return {removedOrphans:removed,deactivatedMissing:missing.length,...(cleanupFailures.length?{cleanupFailures}:{})};
  }
  async reserveStorage(bytes:number,limitBytes:number,root=this.managedRoot):Promise<StorageReservation>{
    let unlock!:()=>void;const previous=this.reservationTail;this.reservationTail=new Promise(resolve=>{unlock=resolve});await previous;
    try{
      const rows=this.db.prepare("SELECT id,file_path,review_status,selected,is_best FROM samples WHERE active=1 ORDER BY quality_score ASC,captured_at ASC").all() as {id:string;file_path:string;review_status:string;selected:number;is_best:number}[];
      const sizes=await Promise.all(rows.map(async r=>({r,size:await stat(r.file_path).then(x=>x.size).catch(()=>0)})));
      const diskUsage=async(dir:string):Promise<number>=>{const entries=await readdir(dir,{withFileTypes:true}).catch(()=>[]);return (await Promise.all(entries.map(entry=>entry.isDirectory()?diskUsage(`${dir}/${entry.name}`):this.reservedFiles.has(path.resolve(dir,entry.name))?0:stat(`${dir}/${entry.name}`).then(x=>x.size).catch(()=>0)))).reduce((a,b)=>a+b,0);};
      let used=await diskUsage(root);for(const x of sizes){if(used+this.reservedBytes+bytes<=limitBytes)break;if(x.r.review_status==='accepted'||x.r.selected||x.r.is_best)continue;await this.deactivate([x.r.id]);used=await diskUsage(root);}
      if(used+this.reservedBytes+bytes>limitBytes)throw new Error(`Training storage limit reached (${Math.round(limitBytes/1024/1024)} MB); accepted samples were preserved`);
      this.reservedBytes+=bytes;let released=false,bound:string|undefined;const commit=()=>{if(released)throw new Error('Storage reservation is already released');return;};const release=()=>{if(released)return;released=true;if(bound)this.reservedFiles.delete(bound);this.reservedBytes-=bytes;unlock();};return {bind:file=>{if(released)throw new Error('Storage reservation is already released');if(bound)this.reservedFiles.delete(bound);bound=path.resolve(file);this.reservedFiles.add(bound);},commit,release};
    }catch(error){unlock();throw error;}
  }
  private map(r:any):ScoredSample{return {id:r.id,ownerId:r.voice_owner_id,filePath:r.file_path,transcript:r.transcript??undefined,durationMs:r.duration_ms,capturedAt:r.captured_at,qualityScore:r.quality_score,speechRatio:r.speech_ratio,silenceRatio:1-r.speech_ratio,rms:r.rms,peak:r.peak,clippingRatio:r.clipping_ratio,snrEstimate:r.snr_estimate,reasons:JSON.parse(r.reasons),isBestSample:!!r.is_best,exceptionalCandidate:!!r.exceptional,selectedForRebuild:!!r.selected,reviewStatus:r.review_status??'pending',active:!!r.active};}
}
