import type { DB } from '../client.js';
export class VoiceRepository {
  constructor(private db:DB){}
  ensureProfile(guild:string,user:string,alias=`voice-${user.slice(-6)}`){const now=Date.now();return this.db.transaction(()=>{let unique=alias.trim()||`voice-${user.slice(-6)}`;const exists=this.db.prepare('SELECT 1 FROM voices WHERE guild_id=? AND alias=? COLLATE NOCASE');if(exists.get(guild,unique))unique=`${unique}-${user.slice(-6)}`;let suffix=2;while(exists.get(guild,unique))unique=`${alias}-${user.slice(-6)}-${suffix++}`;this.db.prepare('INSERT INTO voices(guild_id,owner_id,alias,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,owner_id) DO NOTHING').run(guild,user,unique,now,now);return this.voiceByOwner(guild,user);})();}
  deleteOwnerAndQueue(guild:string,user:string){return this.db.transaction(()=>{const row=this.voiceByOwner(guild,user);if(!row)return undefined;this.db.prepare('DELETE FROM voices WHERE guild_id=? AND owner_id=?').run(guild,user);const remoteId=row.fish_voice_id as string|undefined;if(remoteId){const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable) VALUES(?,?,?,1) ON CONFLICT(remote_id) DO NOTHING').run(remoteId,now,now);}return remoteId;})();}
  voice(guild:string,alias:string){return this.db.prepare('SELECT * FROM voices WHERE guild_id=? AND alias=? COLLATE NOCASE').get(guild,alias) as any;}
  voiceByOwner(guild:string,owner:string){return this.db.prepare('SELECT * FROM voices WHERE guild_id=? AND owner_id=?').get(guild,owner) as any;}
  voices(guild:string){return this.db.prepare('SELECT alias,owner_id,fish_voice_id,model_version,last_rebuilt_at FROM voices WHERE guild_id=? ORDER BY alias').all(guild) as any[];}
  rename(guild:string,user:string,current:string,alias:string){return this.db.prepare('UPDATE voices SET alias=?,updated_at=? WHERE guild_id=? AND owner_id=? AND alias=? COLLATE NOCASE').run(alias,Date.now(),guild,user,current).changes;}
  resetVoiceAndQueue(guild:string,user:string,alias:string){return this.db.transaction(()=>{const row=this.db.prepare('SELECT * FROM voices WHERE guild_id=? AND owner_id=? AND alias=? COLLATE NOCASE').get(guild,user,alias) as any;if(!row)return undefined;this.db.prepare('UPDATE voices SET fish_voice_id=NULL,model_version=0,last_rebuilt_at=NULL,updated_at=? WHERE id=?').run(Date.now(),row.id);const remoteId=row.fish_voice_id as string|undefined;if(remoteId){const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable) VALUES(?,?,?,1) ON CONFLICT(remote_id) DO NOTHING').run(remoteId,now,now);}return remoteId;})();}
  activate(guild:string,user:string,fishId:string,expectedVersion:number){return this.db.prepare('UPDATE voices SET fish_voice_id=?,model_version=?,last_rebuilt_at=?,updated_at=? WHERE guild_id=? AND owner_id=? AND model_version=?').run(fishId,expectedVersion+1,Date.now(),Date.now(),guild,user,expectedVersion).changes===1;}
}
