import type { DB } from '../client.js';
export function normalizeVoiceAlias(value:string){const alias=value.trim();if(!alias||alias.length>64||/[\p{Cc}\p{Cf}\r\n]/u.test(alias)||/@|<[@#&]/.test(alias))throw new Error('Voice alias must be 1-64 characters without controls, newlines, or mentions');return alias;}
export class VoiceRepository {
  constructor(private db:DB){}
  ensureProfile(guild:string,user:string,alias=`voice-${user.slice(-6)}`){const existing=this.voiceByOwner(guild,user);if(existing)return existing;const now=Date.now();return this.db.transaction(()=>{let unique=normalizeVoiceAlias(alias);const exists=this.db.prepare('SELECT 1 FROM voices WHERE guild_id=? AND alias=? COLLATE NOCASE');if(exists.get(guild,unique))unique=normalizeVoiceAlias(`${unique.slice(0,57)}-${user.slice(-6)}`);let suffix=2;while(exists.get(guild,unique))unique=`${normalizeVoiceAlias(alias).slice(0,48)}-${user.slice(-6)}-${suffix++}`;this.db.prepare('INSERT INTO voices(guild_id,owner_id,alias,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,owner_id) DO NOTHING').run(guild,user,unique,now,now);return this.voiceByOwner(guild,user);})();}

  /** @deprecated Compatibility shim; production destructive flows use atomic data/outbox methods below. */
  deleteOwnerAndQueue(guild:string,user:string){const result=this.deleteOwnerDataAndQueue(guild,user);return result.remoteId;}
  /** @deprecated Compatibility shim. */
  resetVoiceAndQueue(guild:string,user:string,voiceId:number){return this.resetVoiceDataAndQueue(guild,user,voiceId).remoteId;}
  voice(guild:string,alias:string){return this.db.prepare('SELECT * FROM voices WHERE guild_id=? AND alias=? COLLATE NOCASE').get(guild,alias) as any;}
  voiceByOwner(guild:string,owner:string){return this.db.prepare('SELECT * FROM voices WHERE guild_id=? AND owner_id=?').get(guild,owner) as any;}
  voices(guild:string){return this.db.prepare('SELECT id,alias,owner_id,fish_voice_id,model_version,state_revision,last_rebuilt_at FROM voices WHERE guild_id=? ORDER BY alias').all(guild) as any[];}
  rename(guild:string,user:string,current:string,alias:string){const normalized=normalizeVoiceAlias(alias);try{return this.db.prepare('UPDATE voices SET alias=?,updated_at=? WHERE guild_id=? AND owner_id=? AND alias=? COLLATE NOCASE').run(normalized,Date.now(),guild,user,current).changes;}catch(error){if(error instanceof Error&&error.message.includes('UNIQUE'))throw new Error('That voice alias is already in use');throw error;}}


  /** @deprecated Test/setup helper; production replacement uses activateReplacementAndQueueOld. */
  activate(guild:string,user:string,fishId:string,expectedVersion:number,expectedRevision:number){return this.db.prepare('UPDATE voices SET fish_voice_id=?,model_version=?,state_revision=state_revision+1,last_rebuilt_at=?,updated_at=? WHERE guild_id=? AND owner_id=? AND model_version=? AND state_revision=?').run(fishId,expectedVersion+1,Date.now(),Date.now(),guild,user,expectedVersion,expectedRevision).changes===1;}
  stageProvider(remoteId:string){this.db.prepare('INSERT OR IGNORE INTO staged_provider_models(remote_id,created_at) VALUES(?,?)').run(remoteId,Date.now());}
  clearStaged(remoteId:string){this.db.prepare('DELETE FROM staged_provider_models WHERE remote_id=?').run(remoteId);}
  abandonStagedAndQueue(remoteId:string){this.db.transaction(()=>{const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable,ready_at) VALUES(?,?,?,1,NULL) ON CONFLICT(remote_id) DO NOTHING').run(remoteId,now,now);this.db.prepare('DELETE FROM staged_provider_models WHERE remote_id=?').run(remoteId);})();}
  reconcileStaged(){return this.db.transaction(()=>{const rows=this.db.prepare('SELECT remote_id FROM staged_provider_models WHERE remote_id NOT IN (SELECT fish_voice_id FROM voices WHERE fish_voice_id IS NOT NULL)').all() as {remote_id:string}[];const now=Date.now(),insert=this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable,ready_at) VALUES(?,?,?,1,NULL) ON CONFLICT(remote_id) DO NOTHING');for(const row of rows)insert.run(row.remote_id,now,now);this.db.prepare('DELETE FROM staged_provider_models').run();return rows.length;})();}
  deleteOwnerDataAndQueue(guild:string,user:string){return this.db.transaction(()=>{const row=this.voiceByOwner(guild,user);const sampleRows=(this.db.prepare('SELECT id,file_path FROM samples WHERE guild_id=? AND voice_owner_id=?').all(guild,user) as {id:string,file_path:string}[]),sampleIds=sampleRows.map(x=>x.id),samplePaths=sampleRows.map(x=>x.file_path);const now=Date.now();for(const file of samplePaths)this.db.prepare('INSERT INTO pending_local_file_deletions(file_path,next_retry_at,created_at) VALUES(?,?,?) ON CONFLICT(file_path) DO NOTHING').run(file,now,now);for(const id of sampleIds)this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?').run(id);this.db.prepare('DELETE FROM samples WHERE guild_id=? AND voice_owner_id=?').run(guild,user);if(row)this.db.prepare('DELETE FROM voices WHERE id=?').run(row.id);const remoteId=row?.fish_voice_id as string|undefined;if(remoteId){const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable,ready_at) VALUES(?,?,?,1,NULL) ON CONFLICT(remote_id) DO NOTHING').run(remoteId,now,now);}return {remoteId,sampleIds,samplePaths};})();}
  resetVoiceDataAndQueue(guild:string,user:string,voiceId:number){return this.db.transaction(()=>{const row=this.db.prepare('SELECT * FROM voices WHERE id=? AND guild_id=? AND owner_id=?').get(voiceId,guild,user) as any;if(!row)return {remoteId:undefined,sampleIds:[] as string[]};const sampleRows=(this.db.prepare('SELECT id,file_path FROM samples WHERE guild_id=? AND voice_owner_id=?').all(guild,user) as {id:string,file_path:string}[]),sampleIds=sampleRows.map(x=>x.id),samplePaths=sampleRows.map(x=>x.file_path);const now=Date.now();for(const file of samplePaths)this.db.prepare('INSERT INTO pending_local_file_deletions(file_path,next_retry_at,created_at) VALUES(?,?,?) ON CONFLICT(file_path) DO NOTHING').run(file,now,now);for(const id of sampleIds)this.db.prepare('DELETE FROM sample_reviews WHERE sample_id=?').run(id);this.db.prepare('DELETE FROM samples WHERE guild_id=? AND voice_owner_id=?').run(guild,user);this.db.prepare('UPDATE voices SET fish_voice_id=NULL,model_version=0,state_revision=state_revision+1,last_rebuilt_at=NULL,updated_at=? WHERE id=?').run(Date.now(),row.id);const remoteId=row.fish_voice_id as string|undefined;if(remoteId){const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable,ready_at) VALUES(?,?,?,1,NULL) ON CONFLICT(remote_id) DO NOTHING').run(remoteId,now,now);}return {remoteId,sampleIds,samplePaths};})();}
  activateReplacementAndQueueOld(guild:string,user:string,fishId:string,expectedVersion:number,expectedRevision:number,selectedIds?:string[]){return this.db.transaction(()=>{const row=this.voiceByOwner(guild,user);if(!row||row.model_version!==expectedVersion||row.state_revision!==expectedRevision)return {activated:false as const};if(selectedIds?.length){const placeholders=selectedIds.map(()=>'?').join(','),valid=(this.db.prepare(`SELECT COUNT(*) count FROM samples WHERE guild_id=? AND voice_owner_id=? AND active=1 AND review_status!='rejected' AND id IN (${placeholders})`).get(guild,user,...selectedIds) as {count:number}).count;if(valid!==selectedIds.length)return {activated:false as const,datasetConflict:true as const};}const oldId=row.fish_voice_id as string|undefined;this.db.prepare('UPDATE voices SET fish_voice_id=?,model_version=?,state_revision=state_revision+1,last_rebuilt_at=?,updated_at=? WHERE id=?').run(fishId,expectedVersion+1,Date.now(),Date.now(),row.id);this.db.prepare('DELETE FROM staged_provider_models WHERE remote_id=?').run(fishId);if(oldId&&oldId!==fishId){const now=Date.now();this.db.prepare('INSERT INTO pending_provider_deletions(remote_id,next_retry_at,created_at,retryable,ready_at) VALUES(?,?,?,1,NULL) ON CONFLICT(remote_id) DO NOTHING').run(oldId,now,now);}return {activated:true as const,oldId};})();}

}
