import {spawn} from 'node:child_process';
import type {PassThrough} from 'node:stream';
import {PublicCommandError} from '../discord/PublicCommandError.js';
import type {MusicSourceResolver,MusicTrack} from './MusicSourceResolver.js';
const youtubeId=/^[A-Za-z0-9_-]{6,20}$/;
export function directYoutubeUrl(input:string){try{const url=new URL(input);if(url.protocol!=='https:')return undefined;if(['youtube.com','www.youtube.com','music.youtube.com'].includes(url.hostname)&&url.pathname==='/watch'){const id=url.searchParams.get('v');return id&&youtubeId.test(id)?`https://www.youtube.com/watch?v=${id}`:undefined;}if(url.hostname==='youtu.be'){const id=url.pathname.slice(1).split('/')[0];return id&&youtubeId.test(id)?`https://youtu.be/${id}`:undefined;}return undefined;}catch{return undefined;}}
export class YtDlpMusicSourceResolver implements MusicSourceResolver {
  private children=new Set<ReturnType<typeof spawn>>();constructor(private binary='yt-dlp'){}
  private run(args:string[],signal?:AbortSignal){return new Promise<string>((resolve,reject)=>{const child=spawn(this.binary,args,{stdio:['ignore','pipe','pipe']});this.children.add(child);let out='',err='';const abort=()=>child.kill('SIGKILL');if(signal?.aborted)abort();signal?.addEventListener('abort',abort,{once:true});child.stdout.setEncoding('utf8').on('data',x=>out+=x);child.stderr.setEncoding('utf8').on('data',x=>{if(err.length<1000)err+=x});child.once('error',reject);child.once('close',code=>{this.children.delete(child);signal?.removeEventListener('abort',abort);if(signal?.aborted)return reject(signal.reason);if(code===0)resolve(out);else reject(new Error(`music resolver exited ${code}: ${err.slice(0,160)}`));});});}
  async resolve(raw:string,requesterId:string,signal?:AbortSignal){const query=raw.trim();if(!query)return undefined;const direct=directYoutubeUrl(query);if(/^https?:\/\//i.test(query)&&!direct)throw new PublicCommandError('Only supported YouTube URLs can be played.');const target=direct??`ytsearch5:${query}`;let output:string;try{output=await this.run(['--dump-single-json','--no-playlist','--skip-download',target],signal);}catch{throw new PublicCommandError(direct?'That YouTube video could not be played.':'That track could not be played.');}const root=JSON.parse(output) as any,entries=(root.entries??[root]).filter(Boolean) as any[];const penalty=(x:any)=>/(reaction|interview|karaoke|slowed|reverb|cover|shorts?|compilation)/i.test(`${x.title} ${x.description??''}`)?1:0;entries.sort((a,b)=>penalty(a)-penalty(b));const item=entries[0];if(!item?.id||!item?.title)return undefined;return {title:String(item.title).slice(0,200),artist:item.artist??item.uploader??item.channel,durationSeconds:typeof item.duration==='number'?item.duration:undefined,sourceId:String(item.id),sourceUrl:`https://www.youtube.com/watch?v=${encodeURIComponent(String(item.id))}`,requesterId} satisfies MusicTrack;}
  async stream(track:MusicTrack,output:PassThrough,signal:AbortSignal){await new Promise<void>((resolve,reject)=>{const child=spawn(this.binary,['--no-playlist','-f','bestaudio','-o','-',track.sourceUrl],{stdio:['ignore','pipe','pipe']});this.children.add(child);let err='';const abort=()=>{child.stdout.unpipe(output);child.kill('SIGKILL');};signal.addEventListener('abort',abort,{once:true});child.stderr.setEncoding('utf8').on('data',x=>{if(err.length<1000)err+=x});child.stdout.pipe(output,{end:false});child.once('error',reject);child.once('close',code=>{this.children.delete(child);signal.removeEventListener('abort',abort);child.stdout.unpipe(output);if(signal.aborted)return resolve();if(code===0)resolve();else reject(new Error(`music stream exited ${code}: ${err.slice(0,160)}`));});});}
  async stopAll(){const children=[...this.children];await Promise.all(children.map(child=>new Promise<void>(resolve=>{if(child.exitCode!==null)return resolve();child.once('close',()=>resolve());child.kill('SIGKILL');})));}
}
