import Database from 'better-sqlite3';
import {mkdirSync} from 'node:fs';
import path from 'node:path';

const samplesSchema=`CREATE TABLE samples(id TEXT PRIMARY KEY,guild_id TEXT NOT NULL DEFAULT '',voice_owner_id TEXT NOT NULL,file_path TEXT NOT NULL,duration_ms INTEGER NOT NULL,captured_at INTEGER NOT NULL,transcript TEXT,quality_score REAL NOT NULL,speech_ratio REAL NOT NULL,rms REAL NOT NULL DEFAULT 0,peak REAL NOT NULL DEFAULT 0,clipping_ratio REAL NOT NULL,snr_estimate REAL NOT NULL,reasons TEXT NOT NULL,is_best INTEGER NOT NULL DEFAULT 0,exceptional INTEGER NOT NULL DEFAULT 0,selected INTEGER NOT NULL DEFAULT 0,review_status TEXT NOT NULL DEFAULT 'pending' CHECK(review_status IN ('pending','accepted','rejected')),active INTEGER NOT NULL DEFAULT 1)`;
export function openDatabase(file:string){
  mkdirSync(path.dirname(file),{recursive:true});const db=new Database(file);db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');
  db.exec(`CREATE TABLE IF NOT EXISTS voices(id INTEGER PRIMARY KEY,guild_id TEXT NOT NULL,owner_id TEXT NOT NULL,alias TEXT NOT NULL COLLATE NOCASE,fish_voice_id TEXT,model_version INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,last_rebuilt_at INTEGER,state_revision INTEGER NOT NULL DEFAULT 0,UNIQUE(guild_id,owner_id),UNIQUE(guild_id,alias));${samplesSchema.replace('CREATE TABLE','CREATE TABLE IF NOT EXISTS')};CREATE TABLE IF NOT EXISTS sample_reviews(id INTEGER PRIMARY KEY, sample_id TEXT NOT NULL, reviewer_id TEXT NOT NULL, decision TEXT NOT NULL, created_at INTEGER NOT NULL);`);
  const voiceColumns=db.prepare('PRAGMA table_info(voices)').all() as {name:string}[];if(!voiceColumns.some(c=>c.name==='state_revision'))db.exec('ALTER TABLE voices ADD COLUMN state_revision INTEGER NOT NULL DEFAULT 0');
  let columns=db.prepare('PRAGMA table_info(samples)').all() as {name:string}[];
  if(!columns.some(c=>c.name==='guild_id')){db.exec("ALTER TABLE samples ADD COLUMN guild_id TEXT NOT NULL DEFAULT ''");columns=db.prepare('PRAGMA table_info(samples)').all() as {name:string}[];}
  if(!columns.some(c=>c.name==='review_status')){db.exec("ALTER TABLE samples ADD COLUMN review_status TEXT NOT NULL DEFAULT 'pending' CHECK(review_status IN ('pending','accepted','rejected'))");db.exec("UPDATE samples SET review_status='accepted' WHERE selected=1");columns=db.prepare('PRAGMA table_info(samples)').all() as {name:string}[];}
  // Remove the legacy overlap column rather than continuing to store a fabricated value.
  if(columns.some(c=>c.name==='overlap_estimate'))db.transaction(()=>{db.exec(`ALTER TABLE samples RENAME TO samples_legacy;${samplesSchema};INSERT INTO samples(id,guild_id,voice_owner_id,file_path,duration_ms,captured_at,transcript,quality_score,speech_ratio,rms,peak,clipping_ratio,snr_estimate,reasons,is_best,exceptional,selected,review_status,active) SELECT id,guild_id,voice_owner_id,file_path,duration_ms,captured_at,transcript,quality_score,speech_ratio,rms,peak,clipping_ratio,snr_estimate,reasons,is_best,exceptional,selected,review_status,active FROM samples_legacy;DROP TABLE samples_legacy`);})();
  db.exec('CREATE TABLE IF NOT EXISTS pending_local_file_deletions(file_path TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,next_retry_at INTEGER NOT NULL,created_at INTEGER NOT NULL,retryable INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS staged_provider_models(remote_id TEXT PRIMARY KEY,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS pending_provider_deletions(remote_id TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,next_retry_at INTEGER NOT NULL,created_at INTEGER NOT NULL,retryable INTEGER NOT NULL DEFAULT 1,ready_at INTEGER)');
  db.exec("CREATE TABLE IF NOT EXISTS application_state(id INTEGER PRIMARY KEY CHECK(id=1),paused INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL,last_error TEXT);INSERT OR IGNORE INTO application_state(id,paused,updated_at) VALUES(1,0,0);CREATE TABLE IF NOT EXISTS backup_status(id INTEGER PRIMARY KEY CHECK(id=1),last_success_at INTEGER,last_success_path TEXT,last_failure_at INTEGER,last_failure TEXT);INSERT OR IGNORE INTO backup_status(id) VALUES(1);CREATE TABLE IF NOT EXISTS model_readiness(guild_id TEXT NOT NULL,owner_id TEXT NOT NULL,dataset_version TEXT NOT NULL,rebuilt_version TEXT,ready INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL,PRIMARY KEY(guild_id,owner_id));");
  const stateColumns=db.prepare('PRAGMA table_info(application_state)').all() as {name:string}[];if(!stateColumns.some(c=>c.name==='last_error'))db.exec('ALTER TABLE application_state ADD COLUMN last_error TEXT');
  const localDeletionColumns=db.prepare('PRAGMA table_info(pending_local_file_deletions)').all() as {name:string}[];if(!localDeletionColumns.some(c=>c.name==='retryable'))db.exec('ALTER TABLE pending_local_file_deletions ADD COLUMN retryable INTEGER NOT NULL DEFAULT 1');
  const deletionColumns=db.prepare('PRAGMA table_info(pending_provider_deletions)').all() as {name:string}[];if(!deletionColumns.some(c=>c.name==='retryable'))db.exec('ALTER TABLE pending_provider_deletions ADD COLUMN retryable INTEGER NOT NULL DEFAULT 1');
  if(!deletionColumns.some(c=>c.name==='ready_at'))db.exec('ALTER TABLE pending_provider_deletions ADD COLUMN ready_at INTEGER');
  db.exec('DROP TABLE IF EXISTS enrollments');db.exec('DROP TABLE IF EXISTS generations');
  return db;
}
export type DB=ReturnType<typeof openDatabase>;
