import {EndBehaviorType,type VoiceConnection} from '@discordjs/voice';
import prism from 'prism-media';
import {randomUUID} from 'node:crypto';
import type {VoiceProvider} from '../services/fish/VoiceProvider.js';import type {TranscriptionService} from '../services/transcription/TranscriptionService.js';import type {DiscordVoiceRuntime} from '../voice/DiscordVoiceRuntime.js';import {wavFromPcm} from '../audio/wav.js';import {LiveVoicePipeline} from './LiveVoicePipeline.js';import {logger} from '../utils/logger.js';
interface Session {pipeline:LiveVoicePipeline;controller:AbortController;detach:()=>void;streams:Set<{destroy:(error?:Error)=>void}>;groupId:string}
export class DiscordLiveService {
  private sessions=new Map<string,Session>();
  constructor(private transcription:TranscriptionService,private fish:VoiceProvider,private voice:DiscordVoiceRuntime,private maxLagMs=3000,private maxUtteranceMs=120_000){}
  start(guild:string,connection:VoiceConnection,sourceUser:string,voiceId:string){
    if(this.sessions.has(guild))throw new Error('Live mode is already active');const pipeline=new LiveVoicePipeline(sourceUser,voiceId,this.maxLagMs);const session:Session={pipeline,controller:new AbortController(),streams:new Set(),groupId:`live:${guild}:${randomUUID()}`,detach:()=>{}};
    const handler=(user:string)=>{if(user!==sourceUser||session.controller.signal.aborted)return;const began=Date.now();const opus=connection.receiver.subscribe(user,{end:{behavior:EndBehaviorType.AfterSilence,duration:350}});const decoder=new prism.opus.Decoder({rate:48_000,channels:2,frameSize:960});session.streams.add(opus);session.streams.add(decoder);const chunks:Buffer[]=[];let bytes=0;decoder.on('data',(b:Buffer)=>{bytes+=b.length;if(bytes<=this.maxUtteranceMs*48_000*2*2/1000)chunks.push(Buffer.from(b));else opus.destroy();});decoder.once('close',()=>{session.streams.delete(opus);session.streams.delete(decoder);});decoder.once('end',()=>void this.process(guild,session,Buffer.concat(chunks),began));opus.on('error',()=>decoder.destroy());opus.pipe(decoder);};
    connection.receiver.speaking.on('start',handler);session.detach=()=>connection.receiver.speaking.off('start',handler);this.sessions.set(guild,session);
  }
  private async process(guild:string,session:Session,pcm:Buffer,began:number){if(pcm.length<9600||session.controller.signal.aborted)return;try{const capture=Date.now()-began;const asrAt=Date.now();const result=await this.transcription.transcribeWav(wavFromPcm(pcm),session.controller.signal);const asr=Date.now()-asrAt;if(!result.text||!session.pipeline.active||session.controller.signal.aborted)return;const queuedAt=Date.now();let firstAudioAt=0;
    this.voice.enqueueStream(guild,`Live: ${result.text.slice(0,50)}`,async(stream,playbackSignal)=>{if(Date.now()-queuedAt>this.maxLagMs)throw new Error('Live utterance discarded because queued backlog became stale');const signal=AbortSignal.any([session.controller.signal,playbackSignal]);await this.fish.streamSynthesize({voiceId:session.pipeline.target(),text:result.text},async chunk=>{if(!firstAudioAt)firstAudioAt=Date.now();if(!stream.write(chunk))await new Promise<void>((resolve,reject)=>{stream.once('drain',resolve);stream.once('error',reject);signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});},signal);const first=firstAudioAt||Date.now();session.pipeline.latency.record({capture,asr,ttsFirstAudio:first-queuedAt,buffer:queuedAt-(asrAt+asr),total:first-began});},session.groupId);
  }catch(err){if(!session.controller.signal.aborted)logger.error({err,guild},'live utterance failed');}}
  stop(guild:string){const session=this.sessions.get(guild);if(!session)return false;session.detach();session.pipeline.stop();session.controller.abort();for(const stream of session.streams)stream.destroy();session.streams.clear();this.voice.cancelGroup(guild,session.groupId);this.sessions.delete(guild);return true;}
  status(guild:string){return this.sessions.get(guild)?.pipeline;}switchVoice(guild:string,id:string){const p=this.status(guild);if(!p)return false;p.switchVoice(id);return true;}
}
