import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,rm,writeFile,stat} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
import {VoiceModelBuilder} from './VoiceModelBuilder.js';import {FishApiError} from '../services/fish/FishClient.js';import type {ScoredSample} from './types.js';
const roots:string[]=[];afterEach(async()=>Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))));
const row=(id:string,filePath:string,qualityScore:number,reviewStatus:'accepted'|'pending'='pending',durationMs=1000):ScoredSample=>({id,ownerId:'u',filePath,durationMs,capturedAt:1,qualityScore,speechRatio:.9,silenceRatio:.1,rms:qualityScore/10,peak:.2,clippingRatio:0,snrEstimate:20,reasons:[],isBestSample:false,exceptionalCandidate:false,selectedForRebuild:false,reviewStatus,active:true});
const files=async(sizes:number[])=>{const root=await mkdtemp(path.join(tmpdir(),'model-upload-'));roots.push(root);return Promise.all(sizes.map(async(size,index)=>{const file=path.join(root,`${index}.wav`);await writeFile(file,Buffer.alloc(size,index+1));return file;}));};
describe('Fish model upload byte budgeting',()=>{
 it('keeps curator priority while count, duration, and byte limits select the exact outbound IDs',async()=>{const paths=await files([400_000,400_000,400_000]),createVoice=vi.fn(async()=>({id:'new'})),samples=[row('accepted',paths[0]!,0.6,'accepted'),row('high',paths[1]!,.99),row('low',paths[2]!,.8)];const builder=new VoiceModelBuilder({createVoice,deleteVoice:vi.fn(),synthesize:vi.fn(),streamSynthesize:vi.fn()} as any,vi.fn(async()=> 'deleted') as any,undefined,2,2,undefined,undefined,undefined,1);const result=await builder.build('voice',samples,vi.fn());expect((createVoice.mock.calls as any)[0][0].references.map((x:any)=>x.path)).toEqual(paths.slice(0,2));expect(result.selectedIds).toEqual(['accepted','high']);expect(await Promise.all(paths.map(x=>stat(x).then(y=>y.size)))).toEqual([400_000,400_000,400_000])});
 it('sends only references fitting the configured budget without mutating originals',async()=>{const paths=await files([700_000,300_000,300_000]),createVoice=vi.fn(async()=>({id:'new'})),samples=paths.map((file,index)=>row(String(index),file,1-index/10));const builder=new VoiceModelBuilder({createVoice,deleteVoice:vi.fn(),synthesize:vi.fn(),streamSynthesize:vi.fn()} as any,vi.fn(async()=> 'deleted') as any,undefined,20,600,undefined,undefined,undefined,1),result=await builder.build('voice',samples,vi.fn());expect((createVoice.mock.calls as any)[0][0].references).toHaveLength(1);expect(result.selectedIds).toEqual(['0']);expect(await Promise.all(paths.map(x=>stat(x).then(y=>y.size)))).toEqual([700_000,300_000,300_000])});
 it('retries 413 with a smaller deterministic subset and stages only the successful model',async()=>{const paths=await files([300_000,300_000,300_000]),createVoice=vi.fn().mockRejectedValueOnce(new FishApiError('too large',413,false)).mockResolvedValue({id:'new'}),stage=vi.fn(),builder=new VoiceModelBuilder({createVoice,deleteVoice:vi.fn(),synthesize:vi.fn(),streamSynthesize:vi.fn()} as any,vi.fn(async()=> 'deleted') as any,undefined,20,600,stage,vi.fn(),undefined,1),result=await builder.build('voice',paths.map((file,index)=>row(String(index),file,1-index/10)),vi.fn());expect(createVoice).toHaveBeenCalledTimes(2);expect((createVoice.mock.calls as any)[0][0].references).toHaveLength(3);expect((createVoice.mock.calls as any)[1][0].references).toHaveLength(1);expect(result.selectedIds).toEqual(['0']);expect(stage).toHaveBeenCalledOnce()});
 it('bounds 413 recovery, does not stage failures, and does not retry unrelated 4xx',async()=>{const [file]=await files([100]),stage=vi.fn(),tooLarge=vi.fn(async()=>{throw new FishApiError('too large',413,false)}),make=(provider:any)=>new VoiceModelBuilder(provider,vi.fn(async()=> 'deleted') as any,undefined,20,600,stage,vi.fn(),undefined,1);await expect(make({createVoice:tooLarge}).build('voice',[row('only',file!,1)],vi.fn())).rejects.toThrow('original recordings were preserved');expect(tooLarge).toHaveBeenCalledOnce();expect(stage).not.toHaveBeenCalled();const bad=vi.fn(async()=>{throw new FishApiError('bad',400,false)});await expect(make({createVoice:bad}).build('voice',[row('only',file!,1)],vi.fn())).rejects.toMatchObject({status:400});expect(bad).toHaveBeenCalledOnce();const many=await files(Array(8).fill(100)),bounded=vi.fn(async()=>{throw new FishApiError('too large',413,false)});await expect(make({createVoice:bounded}).build('voice',many.map((path,index)=>row(String(index),path,1-index/100,'pending',1000+index*500)),vi.fn())).rejects.toThrow('original recordings were preserved');expect(bounded).toHaveBeenCalledTimes(3)});
});
