import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,rm,writeFile,mkdir,readdir,access} from 'node:fs/promises';
import path from 'node:path';import {tmpdir} from 'node:os';
import Database from 'better-sqlite3';
import {openDatabase} from './db/client.js';
import {StateRepository} from './db/repositories/StateRepository.js';
import {ModelReadinessRepository} from './db/repositories/ModelReadinessRepository.js';
import {StorageCoordinator} from './services/StorageCoordinator.js';
import {BackupService} from './services/BackupService.js';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();await Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true})))});
const sample=(id:string)=>({id,ownerId:'234567890123456',durationMs:1000,capturedAt:1,qualityScore:.9,speechRatio:.9,silenceRatio:.1,rms:.1,peak:.2,clippingRatio:0,snrEstimate:10,reasons:[],isBestSample:false,exceptionalCandidate:false,selectedForRebuild:false,reviewStatus:'pending' as const,active:true});
describe('persistent controls',()=>{
 it('keeps paused state across database close and reopen',async()=>{const root=await mkdtemp(path.join(tmpdir(),'state-'));roots.push(root);const file=path.join(root,'bot.db');let db=openDatabase(file);new StateRepository(db).setPaused(true);db.close();db=openDatabase(file);expect(new StateRepository(db).isPaused()).toBe(true);db.close()});
 it('tracks unchanged model datasets without duplicate readiness',()=>{const db=openDatabase(':memory:'),ready=new ModelReadinessRepository(db),rows=[sample('a')];expect(ready.detect('g','u',rows)).toBe(true);ready.rebuilt('g','u',rows);expect(ready.detect('g','u',rows)).toBe(false);expect(ready.detect('g','u',[...rows,sample('b')])).toBe(true);expect(ready.detect('g','u',[])).toBe(false);expect(ready.isReady('g','u')).toBe(false);db.close()});
 it('creates an integrity-checked snapshot and enforces retention',async()=>{const root=await mkdtemp(path.join(tmpdir(),'backup-'));roots.push(root);const data=path.join(root,'data'),backups=path.join(data,'backups');await mkdir(path.join(data,'training'),{recursive:true});await writeFile(path.join(data,'training','sample.wav'),'audio');const db=openDatabase(path.join(data,'bot.db')),state=new StateRepository(db),service=new BackupService(db,state,backups,1,data);db.prepare("INSERT INTO voices(guild_id,owner_id,alias,created_at,updated_at) VALUES('g','u','voice',1,1)").run();await service.run();await new Promise(r=>setTimeout(r,2));await service.run();const names=(await readdir(backups)).filter(x=>x.startsWith('backup-'));expect(names).toHaveLength(1);const snapshot=new Database(path.join(backups,names[0]!,'bot.db'),{readonly:true});expect(snapshot.prepare('SELECT alias FROM voices').pluck().get()).toBe('voice');expect(snapshot.pragma('integrity_check',{simple:true})).toBe('ok');snapshot.close();expect(state.backupStatus().last_success_at).not.toBeNull();db.close()});
 it('holds managed-file mutation behind the database and WAV backup barrier',async()=>{const root=await mkdtemp(path.join(tmpdir(),'backup-barrier-'));roots.push(root);const data=path.join(root,'data'),training=path.join(data,'training'),file=path.join(training,'sample.wav'),backups=path.join(data,'backups');await mkdir(training,{recursive:true});await writeFile(file,'audio');const db=openDatabase(path.join(data,'bot.db')),state=new StateRepository(db),storage=new StorageCoordinator(),service=new BackupService(db,state,backups,1,data,storage);let snapshotStarted!:()=>void,releaseSnapshot!:()=>void;const started=new Promise<void>(resolve=>snapshotStarted=resolve),gate=new Promise<void>(resolve=>releaseSnapshot=resolve),original=db.backup.bind(db);vi.spyOn(db,'backup').mockImplementation(async(destination:any,options:any)=>{snapshotStarted();await gate;return original(destination,options)});const backup=service.run();await started;let removed=false;const mutation=storage.exclusive(async()=>{await rm(file);removed=true});await Promise.resolve();expect(removed).toBe(false);releaseSnapshot();await backup;await mutation;const [name]=(await readdir(backups)).filter(x=>x.startsWith('backup-'));await expect(access(path.join(backups,name!,'training','sample.wav'))).resolves.toBeUndefined();await expect(access(file)).rejects.toThrow();db.close()});
 it('records backup failures without rejecting the runtime call',async()=>{const db=openDatabase(':memory:'),state=new StateRepository(db),service=new BackupService(db,state,'/dev/null/backups',1,'/data');await expect(service.run()).resolves.toBeUndefined();expect(state.backupStatus().last_failure).toBeTruthy();db.close()});
});
