import {describe,it,expect,vi} from 'vitest';import {BestSampleSelector} from './training/BestSampleSelector.js';import {SampleQualityScorer} from './training/SampleQualityScorer.js';import {DatasetCurator} from './training/DatasetCurator.js';import {LiveBuffer} from './live/LiveBuffer.js';import {LiveVoicePipeline} from './live/LiveVoicePipeline.js';import {RateLimiter,isAdmin} from './auth/authorization.js';import {VoiceModelBuilder} from './training/VoiceModelBuilder.js';import {PlaybackQueue} from './voice/PlaybackQueue.js';import type {Features,ScoredSample} from './training/types.js';
const features:Features={durationMs:18000,speechRatio:.91,silenceRatio:.09,rms:.1,peak:.7,clippingRatio:0,snrEstimate:28,continuity:.9};const scored=(id:string,qualityScore=.9,extra:Partial<ScoredSample>={}):ScoredSample=>({...features,id,ownerId:'u',qualityScore,reasons:[],exceptionalCandidate:false,selectedForRebuild:false,isBestSample:false,reviewStatus:'pending',active:true,capturedAt:1,...extra});
describe('quality and best samples',()=>{it('uses multiple signals and identifies exceptional audio',()=>{const s=new SampleQualityScorer().score(features,{id:'a',ownerId:'u'});expect(s.qualityScore).toBeGreaterThan(.9);expect(s.exceptionalCandidate).toBe(true);expect(s.reasons).toContain('No clipping detected');});it('ranks, accepts, rejects and replaces',()=>{const x=new BestSampleSelector();x.add(scored('a',.8));x.add(scored('b',.95));expect(x.top('u',5)[0]?.id).toBe('b');expect(x.accept('u','b')?.selectedForRebuild).toBe(true);expect(x.reject('u','b')?.selectedForRebuild).toBe(false);x.add(scored('c',.97));expect(x.top('u')[0]?.id).toBe('c');});it('preserves accepted samples and selects diverse data',()=>{const c=new DatasetCurator();const a=scored('a',.6,{selectedForRebuild:true});const b=scored('b',.95,{durationMs:22000,rms:.15});const dup=scored('d',.94,{durationMs:22100,rms:.152});expect(c.select([a,b,dup],2).map(x=>x.id)).toEqual(['a','b']);expect(c.prune([a,b,dup],2).removed.map(x=>x.id)).toEqual(['d']);});});
describe('live and controls',()=>{it('drops stale chunks and prevents feedback',()=>{const b=new LiveBuffer<number>(100);b.push(1,0);b.push(2,150);expect(b.shift(150)?.value).toBe(2);const p=new LiveVoicePipeline('source','v1',100);expect(p.accept('bot',new Uint8Array())).toBe(false);expect(p.accept('source',new Uint8Array())).toBe(true);p.switchVoice('v2');expect(p.target()).toBe('v2');});it('authorizes and rate limits centrally',()=>{expect(isAdmin(['a'],'a')).toBe(true);const r=new RateLimiter(1,100);expect(r.allow('x',0)).toBe(true);expect(r.allow('x',1)).toBe(false);expect(r.allow('x',101)).toBe(true);});it('plays sequentially',async()=>{const order:number[]=[];const q=new PlaybackQueue();q.enqueue({id:'1',label:'1',play:async()=>{await new Promise(r=>setTimeout(r,5));order.push(1)}});q.enqueue({id:'2',label:'2',play:async()=>{order.push(2)}});await new Promise(r=>setTimeout(r,20));expect(order).toEqual([1,2]);});});
describe('atomic model replacement',()=>{it('returns validated replacement',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'new'}),synthesize:vi.fn(),deleteVoice:vi.fn()};const out=await new VoiceModelBuilder(provider).build('v',[scored('a',.9,{filePath:'/x',selectedForRebuild:true})],async()=>{});expect(out.id).toBe('new');});it('deletes failed replacement without touching active model',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'bad'}),synthesize:vi.fn(),deleteVoice:vi.fn().mockResolvedValue(undefined)};await expect(new VoiceModelBuilder(provider).build('v',[scored('a',.9,{filePath:'/x'})],async()=>{throw new Error('bad synthesis')})).rejects.toThrow();expect(provider.deleteVoice).toHaveBeenCalledWith('bad');});});

describe('rejection safety',()=>{
  it('advances past a rejected top sample and excludes it from curation and builds',async()=>{
    const selector=new BestSampleSelector();const rejected=scored('bad',.99);const next=scored('next',.9,{durationMs:22000,rms:.2,filePath:'/next.wav'});selector.add(rejected);selector.add(next);selector.reject('u','bad');expect(selector.top('u')[0]?.id).toBe('next');
    expect(new DatasetCurator().select([rejected,next]).map(x=>x.id)).toEqual(['next']);
    const provider={createVoice:vi.fn().mockResolvedValue({id:'new'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()};await new VoiceModelBuilder(provider).build('voice',[rejected,next],async()=>{});expect(provider.createVoice.mock.calls[0]?.[0].references).toEqual([{path:next.filePath}]);
  });
});
describe('failure-safe playback',()=>{it('continues after a failed item and remains reusable',async()=>{const played:number[]=[];const q=new PlaybackQueue();q.enqueue({id:'1',label:'bad',play:async()=>{throw new Error('boom')}});q.enqueue({id:'2',label:'two',play:async()=>{played.push(2)}});await new Promise(r=>setTimeout(r,20));q.enqueue({id:'3',label:'three',play:async()=>{played.push(3)}});await new Promise(r=>setTimeout(r,20));expect(played).toEqual([2,3]);expect(q.list()).toEqual([]);});});
