import {describe,it,expect,vi} from 'vitest';import {SampleFeatureExtractor} from './training/SampleFeatureExtractor.js';import {SampleQualityScorer} from './training/SampleQualityScorer.js';import {DatasetCurator} from './training/DatasetCurator.js';import {RateLimiter} from './auth/authorization.js';import {VoiceModelBuilder} from './training/VoiceModelBuilder.js';import {PlaybackQueue} from './voice/PlaybackQueue.js';import type {Features,ScoredSample} from './training/types.js';
const features:Features={durationMs:18000,speechRatio:.91,silenceRatio:.09,rms:.1,peak:.7,clippingRatio:0,snrEstimate:28,continuity:.9};const scored=(id:string,qualityScore=.9,extra:Partial<ScoredSample>={}):ScoredSample=>({...features,id,ownerId:'u',qualityScore,reasons:[],exceptionalCandidate:false,selectedForRebuild:false,isBestSample:false,reviewStatus:'pending',active:true,capturedAt:1,...extra});
describe('quality and best samples',()=>{it('uses multiple signals and identifies exceptional audio',()=>{const s=new SampleQualityScorer().score(features,{id:'a',ownerId:'u'});expect(s.qualityScore).toBeGreaterThan(.9);expect(s.exceptionalCandidate).toBe(true);expect(s.reasons).toContain('No clipping detected');});it('preserves accepted samples and selects diverse data',()=>{const c=new DatasetCurator();const a=scored('a',.6,{selectedForRebuild:true});const b=scored('b',.95,{durationMs:22000,rms:.15});const dup=scored('d',.94,{durationMs:22100,rms:.152});expect(c.select([a,b,dup],2).map(x=>x.id)).toEqual(['a','b']);expect(c.prune([a,b,dup],2).removed.map(x=>x.id)).toEqual(['d']);});});
describe('controls',()=>{it('authorizes and rate limits centrally',()=>{const r=new RateLimiter(1,100);expect(r.allow('x',0)).toBe(true);expect(r.allow('x',1)).toBe(false);expect(r.allow('x',101)).toBe(true);});it('plays sequentially',async()=>{const order:number[]=[];const q=new PlaybackQueue();q.enqueue({id:'1',label:'1',play:async()=>{await new Promise(r=>setTimeout(r,5));order.push(1)}});q.enqueue({id:'2',label:'2',play:async()=>{order.push(2)}});await new Promise(r=>setTimeout(r,20));expect(order).toEqual([1,2]);});});
describe('atomic model replacement',()=>{it('returns validated replacement',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'new'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()};const out=await new VoiceModelBuilder(provider,async id=>{await provider.deleteVoice(id);return 'deleted' as const}).build('v',[scored('a',.9,{filePath:'/x',selectedForRebuild:true})],async()=>{});expect(out.id).toBe('new');});it('deletes failed replacement without touching active model',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'bad'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn().mockResolvedValue(undefined)};await expect(new VoiceModelBuilder(provider,async id=>{await provider.deleteVoice(id);return 'deleted' as const}).build('v',[scored('a',.9,{filePath:'/x'})],async()=>{throw new Error('bad synthesis')})).rejects.toThrow();expect(provider.deleteVoice).toHaveBeenCalledWith('bad');});});

describe('rejection safety',()=>{
  it('advances past a rejected top sample and excludes it from curation and builds',async()=>{
    const rejected={...scored('bad',.99),reviewStatus:'rejected' as const};const next=scored('next',.9,{durationMs:22000,rms:.2,filePath:'/next.wav'});
    expect(new DatasetCurator().select([rejected,next]).map(x=>x.id)).toEqual(['next']);
    const provider={createVoice:vi.fn().mockResolvedValue({id:'new'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()};await new VoiceModelBuilder(provider,async id=>{await provider.deleteVoice(id);return 'deleted' as const}).build('voice',[rejected,next],async()=>{});expect(provider.createVoice.mock.calls[0]?.[0].references).toEqual([{path:next.filePath}]);
  });
});
describe('failure-safe playback',()=>{it('continues after a failed item and remains reusable',async()=>{const played:number[]=[];const q=new PlaybackQueue();q.enqueue({id:'1',label:'bad',play:async()=>{throw new Error('boom')}});q.enqueue({id:'2',label:'two',play:async()=>{played.push(2)}});await new Promise(r=>setTimeout(r,20));q.enqueue({id:'3',label:'three',play:async()=>{played.push(3)}});await new Promise(r=>setTimeout(r,20));expect(played).toEqual([2,3]);expect(q.list()).toEqual([]);});});

describe('provider limits and PCM VAD',()=>{
  it('hard caps a 200-sample local dataset to 20 Fish references',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'new'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()};const samples=Array.from({length:200},(_,i)=>scored(String(i),1-i/1000,{filePath:`/${i}.wav`,durationMs:10_000+i*400,rms:.02+i*.001,reviewStatus:i<30?'accepted':'pending'}));await new VoiceModelBuilder(provider,async()=> 'deleted' as const,undefined,200,10_000).build('voice',samples,async()=>{});expect(provider.createVoice.mock.calls[0]?.[0].references.length).toBeLessThanOrEqual(20);});
  it.each([
    ['speech and silence',new Int16Array([...new Int16Array(1920),...new Int16Array(1920).fill(6000)]),true],
    ['continuous clean speech',new Int16Array(3840).map((_,i)=>i%2?6000:-6000),true],
    ['silence only',new Int16Array(3840),false],
    ['low background noise',new Int16Array(3840).map((_,i)=>i%2?100:-100),false],
    ['clipped speech',new Int16Array(3840).map((_,i)=>i%2?32767:-32767),true],
  ])('%s',(_name,pcm,speech)=>{const result=new (requireExtractor())().extract(pcm as Int16Array,48000,2);expect(result.speechRatio>0).toBe(speech);});
});
function requireExtractor(){return SampleFeatureExtractor;}

describe('explicit model curation threshold',()=>{it('excludes mediocre pending audio but preserves manual acceptance',()=>{const curator=new DatasetCurator(.78);const pending=scored('pending',.7);const accepted=scored('accepted',.6,{reviewStatus:'accepted'});expect(curator.select([pending,accepted]).map(x=>x.id)).toEqual(['accepted']);});});

describe('provider identifier secrecy',()=>{it('does not put a failed replacement ID in cleanup errors',async()=>{const provider={createVoice:vi.fn().mockResolvedValue({id:'provider-secret-id'}),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()};let message='';try{await new VoiceModelBuilder(provider,async()=> 'retry_scheduled').build('v',[scored('a',.9,{filePath:'/x'})],async()=>{throw new Error('validation failed')});}catch(error){message=error instanceof Error?error.message:String(error);}expect(message).not.toContain('provider-secret-id');expect(message).toContain('cleanup did not complete');});});

describe('maintenance and provider limits',()=>{it('evicts inactive rate-limit keys',()=>{const rate=new RateLimiter(5,10);rate.allow('old',0);for(let i=0;i<99;i++)rate.allow(`u${i}`,100);expect(rate.size()).toBeLessThan(100)});it('protects only the current pending best sample from pruning',()=>{const curator=new DatasetCurator(.8),old=scored('old',.9,{isBestSample:false}),best=scored('best',.7,{isBestSample:true}),rejected=scored('rejected',1,{isBestSample:true,reviewStatus:'rejected'});expect(curator.prune([old,best,rejected],0).removed.map(x=>x.id)).toEqual(['old','rejected']);expect(curator.select([best,rejected])).toEqual([])});});

describe('TTS speed boundary',()=>{it('rejects speeds outside Fish limits before a request',async()=>{const {FishClient}=await import('./services/fish/FishClient.js');await expect(new FishClient('key').synthesize({voiceId:'v',text:'x',speed:.49})).rejects.toThrow('between 0.5 and 2.0');await expect(new FishClient('key').streamSynthesize({voiceId:'v',text:'x',speed:2.01},()=>{})).rejects.toThrow('between 0.5 and 2.0')});});
