import {afterEach,describe,expect,it,vi} from 'vitest';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
import {VoiceModelBuilder} from './training/VoiceModelBuilder.js';import type {ScoredSample} from './training/types.js';import {YtDlpMusicSourceResolver,directYoutubeUrl} from './music/YtDlpMusicSourceResolver.js';import {StorageCoordinator} from './services/StorageCoordinator.js';import {openDatabase} from './db/client.js';import {ModelReadinessRepository} from './db/repositories/ModelReadinessRepository.js';
const roots:string[]=[];afterEach(async()=>{await Promise.all(roots.splice(0).map(x=>rm(x,{recursive:true,force:true})))});
const row=(id:string,filePath:string,quality=.9,extra:Partial<ScoredSample>={}):ScoredSample=>({id,filePath,ownerId:'u',durationMs:10_000,capturedAt:1,qualityScore:quality,speechRatio:.9,silenceRatio:.1,rms:Number(`.1${id.length}`),peak:.5,clippingRatio:0,snrEstimate:20,reasons:[],isBestSample:false,exceptionalCandidate:false,selectedForRebuild:false,reviewStatus:'pending',active:true,...extra});
async function files(count:number,size=10){const root=await mkdtemp(path.join(tmpdir(),'plan-'));roots.push(root);return await Promise.all(Array.from({length:count},async(_,i)=>{const file=path.join(root,`${i}.wav`);await writeFile(file,Buffer.alloc(size));return row(String(i),file,1-i/100,{durationMs:10_000+i*400,rms:.01+i*.01})}));}
const provider=()=>({createVoice:vi.fn(async()=>({id:'new'})),synthesize:vi.fn(),streamSynthesize:vi.fn(),deleteVoice:vi.fn()});
describe('exact effective rebuild plan',()=>{
 it('plans all 20 diverse references when every limit permits them',async()=>{const samples=await files(20);expect((await new VoiceModelBuilder(provider() as any,async()=> 'deleted').plan(samples)).selectedIds).toHaveLength(20);});
 it('applies count, byte, duration, and curator duplicate limits in one plan',async()=>{const samples=await files(20,10),b=new VoiceModelBuilder(provider() as any,async()=> 'deleted',undefined,20,25,undefined,undefined,undefined,35);samples[1]={...samples[1]!,durationMs:samples[0]!.durationMs+1,rms:samples[0]!.rms+0.001};const p=await b.plan(samples);expect(p.candidateCount).toBe(20);expect(p.selectedIds.length).toBeLessThanOrEqual(2);expect(p.selectedBytes).toBeLessThanOrEqual(35);});
 it('records the exact 413-reduced successful subset',async()=>{const samples=await files(4),p=provider();p.createVoice.mockRejectedValueOnce(Object.assign(new Error('large'),{status:413})).mockResolvedValueOnce({id:'new'});const result=await new VoiceModelBuilder(p as any,async()=> 'deleted').build('v',samples,async()=>{});expect(result.selectedIds).toEqual((await new VoiceModelBuilder(p as any,async()=> 'deleted').plan(samples)).selectedIds.slice(0,-1));expect(p.createVoice).toHaveBeenCalledTimes(2);});
 it('ignores low-priority overflow but changes for a displacing high-priority sample',async()=>{const samples=await files(21),b=new VoiceModelBuilder(provider() as any,async()=> 'deleted',undefined,20,600),base=(await b.plan(samples.slice(0,20))).selectedIds,low=(await b.plan(samples)).selectedIds;expect(low).toEqual(base);const high=row('high',samples[20]!.filePath!,2,{durationMs:30_000,rms:.5});expect((await b.plan([...samples.slice(0,20),high])).selectedIds).not.toEqual(base);});
 it('persists exact reduced IDs and treats the unchanged larger plan as up to date',()=>{const db=openDatabase(':memory:'),ready=new ModelReadinessRepository(db);ready.rebuilt('g','u',['a','b']);expect(ready.detect('g','u',['a','b','overflow'])).toBe(false);expect(ready.detect('g','u',['high','a','b'])).toBe(true);expect(JSON.parse((db.prepare('SELECT rebuilt_ids FROM model_readiness').get() as any).rebuilt_ids)).toEqual(['a','b']);db.close()});
});
describe('music resolver safety',()=>{
 it('recognizes exact supported URLs and rejects unrelated URLs',async()=>{expect(directYoutubeUrl('https://youtube.com/watch?v=abc123XYZ')).toContain('abc123XYZ');expect(directYoutubeUrl('https://youtu.be/abc123XYZ')).toContain('abc123XYZ');expect(directYoutubeUrl('https://evil.example/x')).toBeUndefined();await expect(new YtDlpMusicSourceResolver().resolve('https://evil.example/x','u')).rejects.toThrow('Only supported YouTube');});
 it('passes complete text as one safe search argument and direct URLs without search fallback',async()=>{const resolver=new YtDlpMusicSourceResolver(),run=vi.spyOn(resolver as any,'run').mockResolvedValue(JSON.stringify({id:'abc123XYZ',title:'Song'}));await resolver.resolve('новый мерин фараон; --exec','u');expect(run.mock.calls[0]![0]).toContain('ytsearch5:новый мерин фараон; --exec');run.mockClear();await resolver.resolve('https://youtu.be/abc123XYZ','u');expect(run.mock.calls[0]![0]).toContain('https://youtu.be/abc123XYZ');expect(JSON.stringify(run.mock.calls[0]![0])).not.toContain('ytsearch');});
 it('does not search after a failed direct URL',async()=>{const resolver=new YtDlpMusicSourceResolver(),run=vi.spyOn(resolver as any,'run').mockRejectedValue(new Error('fail'));await expect(resolver.resolve('https://youtu.be/abc123XYZ','u')).rejects.toThrow('could not be played');expect(run).toHaveBeenCalledOnce();});
});
it('storage barrier prevents backup from crossing WAV-to-DB admission',async()=>{const storage=new StorageCoordinator();let admit!:()=>void,started!:()=>void;const began=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>admit=r),capture=storage.run(async()=>{started();await gate;}),backup=began.then(()=>storage.run(async()=> 'snapshot'));await began;let crossed=false;void backup.then(()=>crossed=true);await Promise.resolve();expect(crossed).toBe(false);admit();await capture;expect(await backup).toBe('snapshot');});
