import {ChannelType,PermissionFlagsBits} from 'discord.js';
import {loadConfig,dbPath} from './config/env.js';import {openDatabase} from './db/client.js';import {VoiceRepository} from './db/repositories/VoiceRepository.js';import {SampleRepository} from './db/repositories/SampleRepository.js';import {registerCommands} from './discord/registerCommands.js';import {createDiscordClient,drainDiscordInteractions,enableDiscordInteractions} from './discord/client.js';import {TempFiles} from './audio/tempFiles.js';import {logger} from './utils/logger.js';import {FishClient} from './services/fish/FishClient.js';import {DiscordVoiceRuntime} from './voice/DiscordVoiceRuntime.js';import {VoiceCaptureService} from './voice/VoiceCaptureService.js';import {TrainingSessionManager} from './training/TrainingSessionManager.js';import {VoiceModelBuilder} from './training/VoiceModelBuilder.js';import {FishTranscriptionService} from './services/transcription/FishTranscriptionService.js';import {DiscordLiveService} from './live/DiscordLiveService.js';import {ProviderDeletionQueue} from './services/fish/ProviderDeletionQueue.js';import {DatasetCurator} from './training/DatasetCurator.js';import {shutdownRuntime} from './shutdown.js';import {ManagedStorageCleanup} from './services/ManagedStorageCleanup.js';
async function main(){
  process.umask(0o077);const config=loadConfig(),db=openDatabase(dbPath(config.DATABASE_URL));let closed=false;
  const repo=new VoiceRepository(db),samples=new SampleRepository(db);repo.reconcileStaged();await samples.cleanupQueuedFiles();await samples.reconcileManagedStorage();
  const temp=new TempFiles();await temp.init();const fish=new FishClient(config.FISH_API_KEY,'https://api.fish.audio',config.FISH_HTTP_TIMEOUT_MS,config.FISH_TTS_MODEL,config.FISH_REALTIME_MODEL,config.FISH_REALTIME_TIMEOUT_MS),providerDeletions=new ProviderDeletionQueue(db,fish),localCleanup=new ManagedStorageCleanup(samples),voice=new DiscordVoiceRuntime(),capture=new VoiceCaptureService('/data/training',undefined,undefined,config.MAX_TRAINING_SEGMENT_SECONDS*1000,bytes=>samples.reserveStorage(bytes,config.MAX_TRAINING_STORAGE_MB*1024*1024),config.MIN_TRAINING_SEGMENT_SECONDS*1000),training=new TrainingSessionManager(),builder=new VoiceModelBuilder(fish,id=>providerDeletions.delete(id),new DatasetCurator(config.MODEL_SAMPLE_MIN_SCORE),config.FISH_MAX_MODEL_REFERENCES,config.MAX_SELECTED_TRAINING_DURATION_SECONDS,id=>repo.stageProvider(id),id=>repo.clearStaged(id)),transcription=new FishTranscriptionService(config.FISH_API_KEY,'https://api.fish.audio',config.FISH_ASR_TIMEOUT_MS),live=new DiscordLiveService(transcription,fish,voice,config.MAX_LIVE_LAG_MS,config.MAX_LIVE_UTTERANCE_MS),client=createDiscordClient(config,repo,{samples,fish,voice,capture,training,builder,live,providerDeletions},false);
  const cleanup=async()=>{if(closed)return;closed=true;await shutdownRuntime({drainInteractions:()=>drainDiscordInteractions(client),stopCapture:()=>capture.stopAllAndDrain(),stopLive:()=>live.stopAll(),stopVoice:()=>voice.stopAll(),stopLocalCleanup:()=>localCleanup.stopAndDrain(),stopProviderCleanup:()=>providerDeletions.stopAndDrain(),client,db});};
  try{await client.login(config.DISCORD_TOKEN);const guild=await client.guilds.fetch(config.DISCORD_GUILD_ID),channel=await guild.channels.fetch(config.BOT_COMMAND_CHANNEL_ID);if(!channel||channel.guildId!==config.DISCORD_GUILD_ID||channel.type!==ChannelType.GuildText)throw new Error('BOT_COMMAND_CHANNEL_ID must identify a guild text channel in DISCORD_GUILD_ID');const permissions=channel.permissionsFor(client.user!);for(const permission of [PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.AttachFiles])if(!permissions?.has(permission))throw new Error('Bot lacks ViewChannel, SendMessages, or AttachFiles in BOT_COMMAND_CHANNEL_ID');await registerCommands(config.DISCORD_TOKEN,config.DISCORD_CLIENT_ID,config.DISCORD_GUILD_ID);providerDeletions.start();localCleanup.start();enableDiscordInteractions(client);let shuttingDown=false;for(const signal of ['SIGINT','SIGTERM'] as const)process.once(signal,()=>void(async()=>{if(shuttingDown)return;shuttingDown=true;logger.info({signal},'graceful shutdown started');await cleanup();logger.info({signal},'graceful shutdown complete');process.exit(0)})());logger.info('bot started');}catch(error){await cleanup();throw error;}
}
main().catch(error=>{logger.fatal({err:error},'startup failed');process.exitCode=1});
