import {createAudioPlayer,createAudioResource,entersState,joinVoiceChannel,AudioPlayerStatus,NoSubscriberBehavior,StreamType,VoiceConnectionStatus,type VoiceConnection} from '@discordjs/voice';
import {PassThrough,Readable} from 'node:stream';
import {randomUUID} from 'node:crypto';
import {PlaybackQueue} from './PlaybackQueue.js';

interface GuildAudio {connection:VoiceConnection;queue:PlaybackQueue}
/** Preserve synthesized audio as binary chunks; Readable.from(bytes) emits numbers. */
export const binaryPlaybackInput=(bytes:Uint8Array)=>Readable.from([Buffer.from(bytes)]);
export class DiscordVoiceRuntime {
  constructor(private playerFactory:typeof createAudioPlayer=createAudioPlayer,private resourceFactory:typeof createAudioResource=createAudioResource){}
  private guilds=new Map<string,GuildAudio>();
  async join(guildId:string,channelId:string,adapterCreator:any){let existing=this.guilds.get(guildId);if(existing?.connection.state.status===VoiceConnectionStatus.Destroyed){this.guilds.delete(guildId);existing=undefined;}if(existing){if(existing.connection.joinConfig.channelId===channelId){if(existing.connection.state.status!==VoiceConnectionStatus.Ready)await entersState(existing.connection,VoiceConnectionStatus.Ready,20_000);return existing.connection;}try{if(!existing.connection.rejoin({channelId,selfDeaf:false,selfMute:false}))throw new Error('Voice connection rejoin was rejected');await entersState(existing.connection,VoiceConnectionStatus.Ready,20_000);return existing.connection;}catch(error){existing.connection.destroy();this.guilds.delete(guildId);throw error;}}const connection=joinVoiceChannel({guildId,channelId,adapterCreator,selfDeaf:false,selfMute:false});try{await entersState(connection,VoiceConnectionStatus.Ready,20_000);}catch(error){connection.destroy();throw error;}this.guilds.set(guildId,{connection,queue:new PlaybackQueue()});return connection;}
  connection(guildId:string){return this.guilds.get(guildId)?.connection;}
  async leave(guildId:string){const state=this.guilds.get(guildId);if(!state)return false;await state.queue.stop();state.connection.destroy();this.guilds.delete(guildId);return true;}
  queue(guildId:string){const state=this.guilds.get(guildId);if(!state)throw new Error('Join a voice channel first');return state.queue;}
  canEnqueue(guildId:string){return (this.guilds.get(guildId)?.queue.list().length??0)<50;}
  enqueueBytes(guildId:string,label:string,bytes:Uint8Array,_format:'mp3'|'wav'='mp3'){const state=this.guilds.get(guildId);if(!state)throw new Error('Join a voice channel first');if(!this.canEnqueue(guildId))throw new Error('Playback queue is full');const id=randomUUID();state.queue.enqueue({id,label,play:async signal=>{const player=this.playerFactory({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});const resource=this.resourceFactory(binaryPlaybackInput(bytes),{inputType:StreamType.Arbitrary});state.connection.subscribe(player);signal.addEventListener('abort',()=>player.stop(true),{once:true});player.play(resource);await entersState(player,AudioPlayerStatus.Playing,10_000);await new Promise<void>((resolve,reject)=>{player.once(AudioPlayerStatus.Idle,resolve);player.once('error',reject);signal.addEventListener('abort',()=>resolve(),{once:true});});}});return id;}
  enqueueStream(guildId:string,label:string,produce:(stream:PassThrough,signal:AbortSignal)=>Promise<void>,groupId?:string){const state=this.guilds.get(guildId);if(!state)throw new Error('Join a voice channel first');if(!this.canEnqueue(guildId))throw new Error('Playback queue is full');const id=randomUUID();state.queue.enqueue({id,label,groupId,play:async queueSignal=>{const stream=new PassThrough({highWaterMark:64*1024}),producerController=new AbortController(),producerSignal=AbortSignal.any([queueSignal,producerController.signal]);const player=this.playerFactory({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});state.connection.subscribe(player);const abort=()=>{producerController.abort(queueSignal.reason);stream.destroy();player.stop(true);};queueSignal.addEventListener('abort',abort,{once:true});player.play(this.resourceFactory(stream,{inputType:StreamType.Arbitrary}));const generated=produce(stream,producerSignal).then(()=>stream.end()).catch(error=>{stream.destroy();throw error;});void generated.catch(()=>undefined);let cleanup=()=>{};const playback=new Promise<void>((resolve,reject)=>{const idle=()=>{cleanup();resolve()},failed=(error:Error)=>{cleanup();reject(error)};cleanup=()=>{player.off(AudioPlayerStatus.Idle,idle);player.off('error',failed);queueSignal.removeEventListener('abort',cancelled)};const cancelled=()=>{cleanup();resolve()};player.once(AudioPlayerStatus.Idle,idle);player.once('error',failed);queueSignal.addEventListener('abort',cancelled,{once:true});});const producerFailure=generated.then(()=>new Promise<never>(()=>{}),error=>Promise.reject(error));try{await Promise.race([playback,producerFailure]);await generated;}catch(error){producerController.abort(error);stream.destroy();player.stop(true);cleanup();await generated.catch(()=>undefined);throw error;}finally{queueSignal.removeEventListener('abort',abort);cleanup();}}});return id;}
  cancelGroup(guildId:string,groupId:string){return this.guilds.get(guildId)?.queue.cancelGroup(groupId)??0;}
  list(guildId:string){return this.guilds.get(guildId)?.queue.list()??[];}
  skip(guildId:string){return this.guilds.get(guildId)?.queue.skip()??false;}
  async stopAll(){await Promise.all([...this.guilds.keys()].map(guild=>this.leave(guild)));}
  async stop(guildId:string){await this.guilds.get(guildId)?.queue.stop();}
}
